- name: 5.2.1 Ensure permissions on /etc/ssh/sshd_config are configured
  file:
    path: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0600'

- name: 5.2.4 Ensure SSH LogLevel is set to INFO
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^LogLevel'
    insertbefore: BOF
    line: LogLevel INFO

- name: 5.2.5 Ensure SSH X11 forwarding is disabled
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^X11Forwarding'
    insertbefore: BOF
    line: X11Forwarding no

- name: 5.2.6 Ensure SSH MaxAuthTries is set to 4 or less
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^MaxAuthTries'
    insertbefore: BOF
    line: MaxAuthTries 4

- name: 5.2.7 Ensure SSH IgnoreRhosts is enabled
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^IgnoreRhosts'
    insertbefore: BOF
    line: IgnoreRhosts yes

- name: 5.2.8 Ensure SSH HostbasedAuthentication is disabled
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^HostbasedAuthentication'
    insertbefore: BOF
    line: HostbasedAuthentication no

- name: 5.2.9 Ensure SSH root login is disabled
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    insertbefore: BOF
    line: PermitRootLogin no

- name: 5.2.10 Ensure SSH PermitEmptyPasswords is disabled
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitEmptyPasswords'
    insertbefore: BOF
    line: PermitEmptyPasswords no

- name: 5.2.11 Ensure SSH PermitUserEnvironment is disabled
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitUserEnvironment'
    insertbefore: BOF
    line: PermitUserEnvironment no

- name: 5.2.12 Ensure only strong ciphers are used
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^Ciphers'
    insertbefore: BOF
    line: Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr

- name: 5.2.13 Ensure only strong MAC algorithms are used
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^MACs'
    insertbefore: BOF
    line: MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512,hmac-sha2-256

- name: 5.2.14 Ensure only strong key exchange algorithms are used
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: 'KexAlgorithms'
    insertbefore: BOF
    line: KexAlgorithms curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group14-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256

- name: 5.2.15 Ensure SSH Idle Timeout Interval is configured
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^ClientAliveInterval'
    insertbefore: BOF
    line: ClientAliveInterval 300

- name: 5.2.15 Ensure SSH Idle Timeout Interval is configured
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^ClientAliveCountMax'
    insertbefore: BOF
    line: ClientAliveCountMax 3

- name: 5.2.16 Ensure SSH LoginGraceTime is set to one minute or less
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^LoginGraceTime'
    insertbefore: BOF
    line: LoginGraceTime 60

- name: 5.2.17 Ensure SSH access is limited
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^AllowGroups'
    insertbefore: BOF
    line: 'AllowGroups {{ ssh_allow_groups }}'

- name: 5.2.18 Ensure SSH warning banner is configured
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^Banner'
    insertbefore: BOF
    line: Banner /etc/issue.net

- name: 5.2.19 Ensure Pam is enabled
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^UsePAM'
    insertbefore: BOF
    line: UsePAM yes

- name: 5.2.21 Ensure SSH MaxStartups is configured
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^MaxStartups'
    insertbefore: BOF
    line: 'MaxStartups 10:30:60'

- name: 5.2.22 Ensure SSH MaxSessions is limited
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^MaxSessions'
    insertbefore: BOF
    line: 'MaxSessions 10'

- name: 5.3.1 Ensure password creation requirements are configured
  apt:
    name: libpam-pwquality
    state: present

- name: 5.3.1 Ensure password creation requirements are configured
  lineinfile:
    path: /etc/security/pwquality.conf
    regexp: '^minlen'
    line: 'minlen=14'

- name: 5.3.1 Ensure password creation requirements are configured
  lineinfile:
    path: /etc/security/pwquality.conf
    regexp: '^dcredit'
    line: 'dcredit=-1'

- name: 5.3.1 Ensure password creation requirements are configured
  lineinfile:
    path: /etc/security/pwquality.conf
    regexp: '^ucredit'
    line: 'ucredit=-1'

- name: 5.3.1 Ensure password creation requirements are configured
  lineinfile:
    path: /etc/security/pwquality.conf
    regexp: '^ocredit'
    line: 'ocredit=-1'

- name: 5.3.1 Ensure password creation requirements are configured
  lineinfile:
    path: /etc/security/pwquality.conf
    regexp: '^lcredit'
    line: 'lcredit=-1'

- name: 5.4.1.1 Ensure password expiration is 365 days or less
  lineinfile:
    path: /etc/login.defs
    regexp: '^PASS_MAX_DAYS'
    line: 'PASS_MAX_DAYS 365'

- name: 5.4.1.2 Ensure minimum days between password changes is 1 or more
  lineinfile:
    path: /etc/login.defs
    regexp: '^PASS_MIN_DAYS'
    line: 'PASS_MIN_DAYS 1'

- name: 5.4.1.3 Ensure password expiration warning days is 7 or more
  lineinfile:
    path: /etc/login.defs
    regexp: '^PASS_WARN_AGE'
    line: 'PASS_WARN_AGE 7'

- name: 5.6 Ensure access to the su command is restricted
  lineinfile:
    path: /etc/pam.d/su
    regexp: '^auth.*required.*pam_wheel'
    insertafter: '^auth.*sufficient.*pam_rootok'
    line: auth required pam_wheel.so use_uid


