- name: 1.1.1.1 Ensure mounting of cramfs filesystems is disabled
  lineinfile:
    path: /etc/modprobe.d/CIS.conf
    line: install cramfs /bin/true
    create: yes

- name: 1.1.1.2 Ensure mounting of freevxfs filesystems is disabled
  lineinfile:
    path: /etc/modprobe.d/CIS.conf
    line: install freevxfs /bin/true
    create: yes

- name: 1.1.1.3 Ensure mounting of jffs2 filesystems is disabled
  lineinfile:
    path: /etc/modprobe.d/CIS.conf
    line: install jffs2 /bin/true
    create: yes

- name: 1.1.1.4 Ensure mounting of hfs filesystems is disabled
  lineinfile:
    path: /etc/modprobe.d/CIS.conf
    line: install hfs /bin/true
    create: yes

- name: 1.1.1.5 Ensure mounting of hfsplus filesystems is disabled
  lineinfile:
    path: /etc/modprobe.d/CIS.conf
    line: install hfsplus /bin/true
    create: yes

- name: 1.1.1.6 Ensure mounting of udf filesystems is disabled
  lineinfile:
    path: /etc/modprobe.d/CIS.conf
    line: install udf /bin/true
    create: yes

- name: 1.5.2 Ensure permissions on bootloader config are configured
  file:
    path: /boot/grub/grub.cfg
    owner: root
    group: root
    mode: 0600

- name: 1.6.2 Ensure address space layout randomization (ASLR) is enabled
  lineinfile:
    path: /etc/sysctl.d/CIS.conf
    line: 'kernel.randomize_va_space = 2'
    create: yes

- name: 1.5.4 Ensure core dumps are restricted
  lineinfile:
    path: /etc/security/limits.d/CIS.conf
    line: '* hard core 0'
    create: yes

- name: 1.6.4 Ensure core dumps are restricted
  lineinfile:
    path: /etc/sysctl.d/CIS.conf
    line: 'fs.suid_dumpable = 0'
    create: yes

- name: 1.7.1.1 Ensure AppArmor is installed
  apt:
    name: apparmor-profiles
    state: present

- name: 1.7.1.2 Ensure AppArmor is enabled in the bootloader configuration
  file:
    path: /etc/default/grub.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: 1.7.1.2 Ensure AppArmor is enabled in the bootloader configuration
  copy:
    content: 'GRUB_CMDLINE_LINUX_DEFAULT="$GRUB_CMDLINE_LINUX_DEFAULT apparmor=1 security=apparmor"'
    dest: /etc/default/grub.d/apparmor.cfg
    owner: root
    group: root
    mode: 0644

- name: 1.7.1.2 Ensure AppArmor is enabled in the bootloader configuration
  command:
    cmd: /usr/sbin/update-grub

- name: 1.8.1.2 Ensure local login warning banner is configured properly
  copy:
    content: "{{ logon_banner }}"
    dest: /etc/issue
    owner: root
    group: root
    mode: 0644

- name: 1.8.1.3 Ensure remote login warning banner is configured properly
  copy:
    content: "{{ logon_banner }}"
    dest: /etc/issue.net
    owner: root
    group: root
    mode: 0644

- name: 1.8.1.4 Ensure permissions on /etc/motd are configured
  file:
    path: /etc/motd
    state: touch
    owner: root
    group: root
    mode: 0644

- name: 1.8.1.5 Ensure permissions on /etc/issue are configured
  file:
    path: /etc/issue
    owner: root
    group: root
    mode: 0644

- name: 1.8.1.6 Ensure permissions on /etc/issue.net are configured
  file:
    path: /etc/issue.net
    owner: root
    group: root
    mode: 0644
